---
title: "intro_to_r_mkdwn"
author: "KARIITHI"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

# import data
ideal1 <- read_csv("ideal1.csv")
ideal2 <- read_csv("ideal2.csv")

# Merge Data
ideal3 <- full_join(ideal1, ideal2, by = "CalfID") |>
  mutate(CalfSex = recode(CalfSex, "1"="Male" , "2"="Female")) |> 
  mutate(ReasonsLoss = recode (ReasonsLoss, "6"="Sold" , "7"="Death", "12"="Relocation", "18"="Refusal")) |>
  mutate(CADOB = dmy(CADOB)) |>
  mutate(VisitDate = dmy(VisitDate)) |>
  
  # Create a new column called visitNo, the divides the VisitID to extract the unique character to give the visit time which is the 4th index
  mutate(visitNo = str_sub (VisitID, 4, 5))|>
  
  # group the data by calfID
  group_by(CalfID) |>
  
  # Create a new column to display the max and min weights of the calf
  mutate(max_weight = max(Weight, na.rm = TRUE)) |># Maximum Weight
  mutate(min_weight = min(Weight, na.rm = TRUE)) |># Minimum Weight
  
  # Good practice
  ungroup() |>
  
  # Grouping the test using if else
  mutate(ManualPCV = ifelse(ManualPCV < 30, "Negative", "Positive")) |>
  mutate(Theileria.spp.= ifelse(Theileria.spp. == 1, "Positive", "Negative")) |>
  mutate(ELISA_mutans = ifelse(ELISA_mutans == 1, "Positive", "Negative")) |>
  mutate(ELISA_parva = ifelse(ELISA_parva == 1, "Positive", "Negative")) |>
 #mutate_all(vars(Theileria.spp., ELISA_mutans,ELISA_parva), funs(ifelse(.==1,"Positive, "Negative")))|>
  mutate(Q.Strongyle.eggs = ifelse(Q.Strongyle.eggs < 700, "Negative", "Positive"))
```

```{r}
# Transpose data : to long column
calf_tests <- ideal3 |>
  select(CalfID, ManualPCV, Theileria.spp., ELISA_mutans, ELISA_parva, Q.Strongyle.eggs) |>
  pivot_longer(c( ManualPCV, Theileria.spp., ELISA_mutans, ELISA_parva, Q.Strongyle.eggs),names_to = "Tests", values_to = "Results") |>
  group_by(Tests, Results)|>
  summarise(count = n()) |>
  na.omit()|>
  ungroup()|>
  
  # find the percentages of the counts with reference to the total number of +ves and  -ves
  group_by(Tests)|>
  
  #create a new column called total to get the sum of the counts
  mutate(Total = sum(count))|>
  ungroup() |>
  
  # we divide the count and total. To find the percentage and put it in a new column called Proportion
  #Add round to the nearest whole number
  mutate(Proportion = round(count / Total * 100))
```
```{r}
 ggplot(calf_tests, aes(x = Proportion, y=Tests, fill = Results)) + geom_col()
```

```{r, shapefiles}

#install.packages(c("sf","devtools"))
library(sf)

# import data
kenya <- st_read("shapefiles/gadm41_KEN_0.shp")

# plot data
ggplot(kenya) + geom_sf()

```
```{r}
# import county data
counties <- st_read("shapefiles/gadm41_KEN_1.shp")

# plot data
ggplot(counties) + geom_sf()


# Install the kenya censors data from Github using devtools

devtools::install_github("Shelmith-Kariuki/rKenyaCensus")
library(rKenyaCensus)

# Datacatalogue
census_data <- V1_T2.2 |>
   mutate(County = recode (County, "Taita/Taveta"="Taita Taveta" , "Nairobi City"="Nairobi", "Elgeyo/Marakwet"="Elgeyo-Marakwet"))

#
setdiff(counties$NAME_1, census_data$County)

# do a join
counties1 <- left_join(counties, census_data, by=c("NAME_1"="County"))

install.packages("ggspatial")
# plot the counties on the map
ggplot(counties1) + geom_sf(aes(fill = Total)) + 
scale_fill_gradient(low = "#fff7bc", high ="darkred") +theme_void()+
  ggspatial::annotation_north_arrow(location = "tr")+
  ggspatial::annotation_scale()

```

```



